<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IFOCUS-PC43" name="Test" tests="15" failures="12" timestamp="11 May 2018 09:47:14 GMT" time="119.609" errors="0">
  <testcase name="Login_Kids" time="5.004" classname="API_VootKids.Login">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
JSON path kToken doesn&amp;apos;t match.
Expected: is not null
  Actual: null
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
JSON path kToken doesn't match.
Expected: is not null
  Actual: null

	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:598)
	at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:760)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.content(ResponseSpecificationImpl.groovy:251)
	at com.jayway.restassured.specification.ResponseSpecification$content$1.callCurrent(Unknown Source)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:234)
	at com.jayway.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:264)
	at API_VootKids.Login.Login_Kids(Login.java:130)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Login_Kids -->
  <testcase name="Forgot_Password" time="4.174" classname="API_VootKids.ForgotPassword">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Email address does not exist] but found [User does not exist.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Email address does not exist] but found [User does not exist.]
	at API_VootKids.ForgotPassword.Forgot_Password(ForgotPassword.java:115)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Forgot_Password -->
  <testcase name="SignUp_Kids" time="13.797" classname="API_VootKids.UpdateProfile">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Invalid childProfileId.] but found [This unique record Id is invalid, please enter a valid unique record ID.],
	expected [Invalid childProfileId.] but found [This unique record Id is invalid, please enter a valid unique record ID.],
	expected [Please enter a valid profile name.] but found [The profile.name may only contain letters.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Invalid childProfileId.] but found [This unique record Id is invalid, please enter a valid unique record ID.],
	expected [Invalid childProfileId.] but found [This unique record Id is invalid, please enter a valid unique record ID.],
	expected [Please enter a valid profile name.] but found [The profile.name may only contain letters.]
	at API_VootKids.UpdateProfile.SignUp_Kids(UpdateProfile.java:252)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- SignUp_Kids -->
  <testcase name="reset_Password" time="6.044" classname="API_VootKids.ResetPassword">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Invalid user ID and/or password] but found [Password reset was successful.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Invalid user ID and/or password] but found [Password reset was successful.]
	at API_VootKids.ResetPassword.reset_Password(ResetPassword.java:161)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- reset_Password -->
  <testcase name="reset_Pin" time="5.895" classname="API_VootKids.ResetPin">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Incorrect old pin.] but found [Pin reset was successful.],
	expected [Email address does not exist] but found [The provided email address does not exist, please use a valid email address.],
	expected [Email address does not exist] but found [The provided email address does not exist, please use a valid email address.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Incorrect old pin.] but found [Pin reset was successful.],
	expected [Email address does not exist] but found [The provided email address does not exist, please use a valid email address.],
	expected [Email address does not exist] but found [The provided email address does not exist, please use a valid email address.]
	at API_VootKids.ResetPin.reset_Pin(ResetPin.java:161)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- reset_Pin -->
  <testcase name="Create_Profiles" time="8.203" classname="API_VootKids.CreateProfile">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
JSON path refreshToken doesn&amp;apos;t match.
Expected: is not null
  Actual: null
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
JSON path refreshToken doesn't match.
Expected: is not null
  Actual: null

	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:598)
	at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:760)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.content(ResponseSpecificationImpl.groovy:251)
	at com.jayway.restassured.specification.ResponseSpecification$content$1.callCurrent(Unknown Source)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:234)
	at com.jayway.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:264)
	at API_VootKids.CreateProfile.Create_Profiles(CreateProfile.java:247)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Create_Profiles -->
  <testcase name="Swith_Profile" time="2.264" classname="API_VootKids.SwitchProfile">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
JSON path $ doesn&amp;apos;t match.
Expected: map containing [&amp;quot;kID&amp;quot;-&amp;gt;ANYTHING]
  Actual: {status={code=403, message=User does not exist}}
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
JSON path $ doesn't match.
Expected: map containing ["kID"->ANYTHING]
  Actual: {status={code=403, message=User does not exist}}

	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:598)
	at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:760)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.content(ResponseSpecificationImpl.groovy:251)
	at com.jayway.restassured.specification.ResponseSpecification$content$1.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at com.jayway.restassured.specification.ResponseSpecification$content$1.callCurrent(Unknown Source)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:234)
	at com.jayway.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:264)
	at API_VootKids.SwitchProfile.Swith_Profile(SwitchProfile.java:116)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Swith_Profile -->
  <testcase name="CreatePin1" time="53.255" classname="API_VootKids.CreatePin">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Email address does not exist] but found [The provided email address does not exist, please use a valid email address.],
	expected [Email address does not exist] but found [The provided email address does not exist, please use a valid email address.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Email address does not exist] but found [The provided email address does not exist, please use a valid email address.],
	expected [Email address does not exist] but found [The provided email address does not exist, please use a valid email address.]
	at API_VootKids.CreatePin.CreatePin1(CreatePin.java:175)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- CreatePin1 -->
  <testcase name="Get_ChildProfiles" time="4.453" classname="API_VootKids.GetProfile"/>
  <testcase name="SignUp_Kids" time="3.019" classname="API_VootKids.SignUp">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at API_VootKids.GenericMethod.SignUp(GenericMethod.java:77)
	at API_VootKids.SignUp.SignUp_Kids(SignUp.java:45)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SignUp_Kids -->
  <testcase name="tabs" time="0.213" classname="API_VootKids.Tabs"/>
  <testcase name="config" time="0.217" classname="API_VootKids.Config"/>
  <testcase name="Social_Login" time="2.144" classname="API_VootKids.SocialLogin">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
JSON path kToken doesn&amp;apos;t match.
Expected: is not null
  Actual: null
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
JSON path kToken doesn't match.
Expected: is not null
  Actual: null

	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:598)
	at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:760)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.content(ResponseSpecificationImpl.groovy:251)
	at com.jayway.restassured.specification.ResponseSpecification$content$1.callCurrent(Unknown Source)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:234)
	at com.jayway.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:264)
	at API_VootKids.SocialLogin.Social_Login(SocialLogin.java:109)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Social_Login -->
  <testcase name="home" time="5.664" classname="API_VootKids.Home">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected [uId parameter is required] but found [Invalid Uid],
	expected [profileId parameter is required] but found [Invalid Profile Id],
	expected [ks parameter is required] but found [Invalid Ks value]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected [uId parameter is required] but found [Invalid Uid],
	expected [profileId parameter is required] but found [Invalid Profile Id],
	expected [ks parameter is required] but found [Invalid Ks value]
	at API_VootKids.Home.home(Home.java:218)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- home -->
  <testcase name="Forgot_Pin" time="5.196" classname="API_VootKids.ForgotPin">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Email address does not exist] but found [User does not exist.],
	expected [Email address does not exist] but found [User does not exist.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Email address does not exist] but found [User does not exist.],
	expected [Email address does not exist] but found [User does not exist.]
	at API_VootKids.ForgotPin.Forgot_Pin(ForgotPin.java:115)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Forgot_Pin -->
</testsuite> <!-- Test -->
