<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="15" passed="11">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="402028" started-at="2018-04-30T11:56:41Z" finished-at="2018-04-30T12:03:23Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="402028" started-at="2018-04-30T11:56:41Z" finished-at="2018-04-30T12:03:23Z">
      <class name="API_VootKids.ForgotPin">
        <test-method status="PASS" signature="Forgot_Pin()[pri:0, instance:API_VootKids.ForgotPin@60c6f5b]" name="Forgot_Pin" duration-ms="5408" started-at="2018-04-30T17:32:38Z" finished-at="2018-04-30T17:32:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Forgot_Pin -->
      </class> <!-- API_VootKids.ForgotPin -->
      <class name="API_VootKids.SignUp">
        <test-method status="PASS" signature="SignUp_Kids()[pri:0, instance:API_VootKids.SignUp@71318ec4]" name="SignUp_Kids" duration-ms="26136" started-at="2018-04-30T17:31:51Z" finished-at="2018-04-30T17:32:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignUp_Kids -->
      </class> <!-- API_VootKids.SignUp -->
      <class name="API_VootKids.CreatePin">
        <test-method status="PASS" signature="CreatePin1()[pri:0, instance:API_VootKids.CreatePin@7e0b0338]" name="CreatePin1" duration-ms="58333" started-at="2018-04-30T17:26:55Z" finished-at="2018-04-30T17:27:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatePin1 -->
      </class> <!-- API_VootKids.CreatePin -->
      <class name="API_VootKids.Tabs">
        <test-method status="PASS" signature="tabs()[pri:0, instance:API_VootKids.Tabs@3327bd23]" name="tabs" duration-ms="392" started-at="2018-04-30T17:33:03Z" finished-at="2018-04-30T17:33:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tabs -->
      </class> <!-- API_VootKids.Tabs -->
      <class name="API_VootKids.CreateProfile">
        <test-method status="FAIL" signature="Create_Profiles()[pri:0, instance:API_VootKids.CreateProfile@617faa95]" name="Create_Profiles" duration-ms="206342" started-at="2018-04-30T17:28:06Z" finished-at="2018-04-30T17:31:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [The profile.name may only contain letters.] but found [OK],
	expected [Client error: `POST https://rest-sgs1.ott.kaltura.com/restful_v4_4/api_v3/service/householddevice/action/add` resulted in a `404 Not Found` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml (truncated...)
] but found [UserDoesNotExist],
	expected [Client error: `POST https://rest-sgs1.ott.kaltura.com/restful_v4_4/api_v3/service/householddevice/action/add` resulted in a `404 Not Found` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml (truncated...)
] but found [UserDoesNotExist]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [The profile.name may only contain letters.] but found [OK],
	expected [Client error: `POST https://rest-sgs1.ott.kaltura.com/restful_v4_4/api_v3/service/householddevice/action/add` resulted in a `404 Not Found` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml (truncated...)
] but found [UserDoesNotExist],
	expected [Client error: `POST https://rest-sgs1.ott.kaltura.com/restful_v4_4/api_v3/service/householddevice/action/add` resulted in a `404 Not Found` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml (truncated...)
] but found [UserDoesNotExist]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at API_VootKids.CreateProfile.Create_Profiles(CreateProfile.java:300)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Create_Profiles -->
      </class> <!-- API_VootKids.CreateProfile -->
      <class name="API_VootKids.Home">
        <test-method status="FAIL" signature="home()[pri:0, instance:API_VootKids.Home@3c0f93f1]" name="home" duration-ms="4741" started-at="2018-04-30T17:27:54Z" finished-at="2018-04-30T17:27:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected [uId parameter is required] but found [Invalid Uid],
	expected [profileId parameter is required] but found [Invalid Profile Id],
	expected [ks parameter is required] but found [Invalid Ks value]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected [uId parameter is required] but found [Invalid Uid],
	expected [profileId parameter is required] but found [Invalid Profile Id],
	expected [ks parameter is required] but found [Invalid Ks value]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at API_VootKids.Home.home(Home.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- home -->
      </class> <!-- API_VootKids.Home -->
      <class name="API_VootKids.ResetPin">
        <test-method status="PASS" signature="reset_Pin()[pri:0, instance:API_VootKids.ResetPin@31610302]" name="reset_Pin" duration-ms="7607" started-at="2018-04-30T17:27:58Z" finished-at="2018-04-30T17:28:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reset_Pin -->
      </class> <!-- API_VootKids.ResetPin -->
      <class name="API_VootKids.UpdateProfile">
        <test-method status="FAIL" signature="SignUp_Kids()[pri:0, instance:API_VootKids.UpdateProfile@4e1d422d]" name="SignUp_Kids" duration-ms="19608" started-at="2018-04-30T17:33:03Z" finished-at="2018-04-30T17:33:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [Unable to retrieve updated profile.] but found [This Account ID is invalid, please use valid account ID.],
	expected [Unable to retrieve updated profile.] but found [This Account ID is invalid, please use valid account ID.],
	expected [Unable to retrieve updated profile.] but found [This unique record Id is invalid, please enter a valid unique record ID.],
	expected [Unable to retrieve updated profile.] but found [This unique record Id is invalid, please enter a valid unique record ID.],
	expected [The profile.name may only contain letters.] but found [OK]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Unable to retrieve updated profile.] but found [This Account ID is invalid, please use valid account ID.],
	expected [Unable to retrieve updated profile.] but found [This Account ID is invalid, please use valid account ID.],
	expected [Unable to retrieve updated profile.] but found [This unique record Id is invalid, please enter a valid unique record ID.],
	expected [Unable to retrieve updated profile.] but found [This unique record Id is invalid, please enter a valid unique record ID.],
	expected [The profile.name may only contain letters.] but found [OK]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at API_VootKids.UpdateProfile.SignUp_Kids(UpdateProfile.java:252)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignUp_Kids -->
      </class> <!-- API_VootKids.UpdateProfile -->
      <class name="API_VootKids.ResetPassword">
        <test-method status="PASS" signature="reset_Password()[pri:0, instance:API_VootKids.ResetPassword@544fe44c]" name="reset_Password" duration-ms="7939" started-at="2018-04-30T17:26:47Z" finished-at="2018-04-30T17:26:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reset_Password -->
      </class> <!-- API_VootKids.ResetPassword -->
      <class name="API_VootKids.ForgotPassword">
        <test-method status="PASS" signature="Forgot_Password()[pri:0, instance:API_VootKids.ForgotPassword@1e127982]" name="Forgot_Password" duration-ms="4134" started-at="2018-04-30T17:32:18Z" finished-at="2018-04-30T17:32:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Forgot_Password -->
      </class> <!-- API_VootKids.ForgotPassword -->
      <class name="API_VootKids.Login">
        <test-method status="PASS" signature="Login_Kids()[pri:0, instance:API_VootKids.Login@31dc339b]" name="Login_Kids" duration-ms="19081" started-at="2018-04-30T17:31:32Z" finished-at="2018-04-30T17:31:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_Kids -->
      </class> <!-- API_VootKids.Login -->
      <class name="API_VootKids.GetProfile">
        <test-method status="PASS" signature="Get_ChildProfiles()[pri:0, instance:API_VootKids.GetProfile@2038ae61]" name="Get_ChildProfiles" duration-ms="4811" started-at="2018-04-30T17:26:43Z" finished-at="2018-04-30T17:26:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Get_ChildProfiles -->
      </class> <!-- API_VootKids.GetProfile -->
      <class name="API_VootKids.SocialLogin">
        <test-method status="PASS" signature="Social_Login()[pri:0, instance:API_VootKids.SocialLogin@21213b92]" name="Social_Login" duration-ms="16234" started-at="2018-04-30T17:32:22Z" finished-at="2018-04-30T17:32:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Social_Login -->
      </class> <!-- API_VootKids.SocialLogin -->
      <class name="API_VootKids.SwitchProfile">
        <test-method status="FAIL" signature="Swith_Profile()[pri:0, instance:API_VootKids.SwitchProfile@a67c67e]" name="Swith_Profile" duration-ms="19394" started-at="2018-04-30T17:32:43Z" finished-at="2018-04-30T17:33:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [This unique record Id is invalid, please enter a valid unique record ID.] but found [Invalid ChildProfileId],
	expected [This unique record Id is invalid, please enter a valid unique record ID.] but found [Invalid ChildProfileId]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [This unique record Id is invalid, please enter a valid unique record ID.] but found [Invalid ChildProfileId],
	expected [This unique record Id is invalid, please enter a valid unique record ID.] but found [Invalid ChildProfileId]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at API_VootKids.SwitchProfile.Swith_Profile(SwitchProfile.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Swith_Profile -->
      </class> <!-- API_VootKids.SwitchProfile -->
      <class name="API_VootKids.Config">
        <test-method status="PASS" signature="config()[pri:0, instance:API_VootKids.Config@dc24521]" name="config" duration-ms="1836" started-at="2018-04-30T17:26:41Z" finished-at="2018-04-30T17:26:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config -->
      </class> <!-- API_VootKids.Config -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
